[Document Link](https://docs.google.com/document/d/1MTEprKJhf1dqwSZp79tSjYsxaovsE48aLtE9FF-E9BU/edit?usp=sharing)

## Array Creation

In [5]:
list1 = [2,4,5,7,8]
print(type(list1))
list1

<class 'list'>


[2, 4, 5, 7, 8]

In [8]:
# Create an array out of list
# Importing numpy library
import numpy as np
arr1 = np.array(list1)
print(type(arr1))
arr1   # <class 'numpy.ndarray'> --> N-Dimensional Array

<class 'numpy.ndarray'>


array([2, 4, 5, 7, 8])

In [9]:
# Using arange to create an array of 2 D
# arange --> similar to range(start, stop), where stop value is not included
# arange(start, stop, step)--> default start value is 0
arr2 = np.arange(10) # arange(start, stop)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# With start value as 0 
arr2 = np.arange(start=0, stop=10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr3 = np.arange(start=1, stop=10, step=2)
arr3


array([1, 3, 5, 7, 9])

In [16]:
# Attributes
print(arr2)
arr2.ndim

[0 1 2 3 4 5 6 7 8 9]


1

In [22]:
# reshape--> to the new dimension; 5*2 or 2*5
arr2 = arr2.reshape(5,2)
print(arr2.ndim)
print(arr2)

2
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [31]:
# Array Attributes
print(arr1)
print(arr1.shape)  # returns the nrows*ncols
print(arr1.size)  # total number of elements in the array
print(arr1.itemsize) # number of bytes required to store the elements
print(arr1.dtype) # data type of the array

[2 4 5 7 8]
(5,)
5
4
int32


In [26]:
arr2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [33]:
# Indexing
arr2[3][1]

7

In [35]:
# Sub-array with row indices 0, 1, 2
arr2[:3]

array([[0, 1],
       [2, 3],
       [4, 5]])

In [40]:
# : indicates all
print(arr2)
print(arr2[:, 1])


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[1 3 5 7 9]


In [43]:
# linspace--> linearly spaced values in an interval
a = np.linspace(start =1, stop =10, num= 5)
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [45]:
# linspace--> linearly spaced values in an interval
a = np.linspace(start =1, stop =10, num= 12)
a

array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

In [48]:
# Use arange and reshape in a single line
b = np.arange(20).reshape(5,4)  # 20 values--> 2 * 10, 10* 2, 5 *4, 4*5
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [49]:
# Convert 2 D array to 1D array
c = b.ravel()
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [51]:
print(b)
b.min() # returns the minimum value

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


0

In [52]:
# argmin() --> the index of the mimimum value to be returned
b.argmin()

0

In [59]:
print(a)
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

[ 1.          1.81818182  2.63636364  3.45454545  4.27272727  5.09090909
  5.90909091  6.72727273  7.54545455  8.36363636  9.18181818 10.        ]
1.0
0
10.0
11


In [61]:
print(a.sum()) # returns the sum of all the elements
np.sqrt(a)

66.0


array([1.        , 1.34839972, 1.62368828, 1.85864075, 2.06705764,
       2.2563043 , 2.43086217, 2.59369866, 2.74689908, 2.89199522,
       3.03015151, 3.16227766])

####  Stacking Arrays

In [63]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(11,20).reshape(3,3) #
print(a)
b

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [65]:
# hstack
np.hstack((a,b))

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [66]:
# vstack
np.vstack([a,b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [67]:
a = np.arange(8).reshape(2, 4) # 2 rows, 4 cols
b = np.arange(2).reshape(2,1)
np.hstack([a,b])

array([[0, 1, 2, 3, 0],
       [4, 5, 6, 7, 1]])

In [68]:
a  # x*x-5

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [69]:
b

array([[0],
       [1]])

### Applying User-Defined Functions

In [75]:
# Creating a function
def calculate(x):
    return x*x-5
calculate(45)

2020

In [72]:
cal = np.vectorize(calculate)
cal([1,2,3,4])

array([-4, -1,  4, 11])

In [74]:
print(b)
cal(b)

[[0]
 [1]]


array([[-5],
       [-4]])

### Random Module from Numpy

In [105]:
from numpy import random
r = np.random.RandomState(1)
a = r.rand() # 0 to 1
print(a)
np.round(a, decimals=1)

0.417022004702574


0.4

In [126]:
random.randint(100) # returns the random integer in the specified range
arr = random.randint(100, size=(2,2))
arr

array([[89, 93],
       [29,  8]])

In [128]:
# choice() - allows to generate a random value based on an array of values.

random.choice(arr.ravel()) # arr is 2 D--> convert it into 1D array with help of ravel

93

In [125]:
random.seed(10)
random.choice([1,2,3,4,5], size=(2,2))

array([[2, 5],
       [1, 2]])