Numpy matrices are strictly 2-dimensional, while numpy arrays (ndarrays) are N-dimensional. Matrix objects are a subclass of ndarray, so they inherit all the attributes and methods of ndarrays.

The main advantage of numpy matrices is that they provide a convenient notation for matrix multiplication: if a and b are matrices, then a*b is their matrix product.

**NumPy** is a core-library for scientific computing in Python which provides high performance multidimentional array objects as well as concern tools or attributes for working on these array objects.


In this notebook  following content will be covered.

- NumPy Array Objects
- Difference between Numpy and Python Lists
- Array Attributes
- Slicing
- Boolean Indexing 
- Appending Arrays 
- Functions
- Getting Empty Arrays
- Applying User-Defined Functions
- Math Operations

### Array Creation

In [1]:
import numpy as np
l1 = [1,2,3,4,5,6,7,8,9]

# convert list to ndarray using numpy array function
a1 = np.array(l1)
print(type(a1))
a1

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [2]:
# Creating an array using arange function
a1 = np.arange(10)
b = np.arange(-5,10)

print(a1.dtype)
print(type(a1))
print(a1)
b

int32
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]


array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [3]:
l2 = list(range(1,11))
l2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [2]:

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


2

In [4]:
a2 = np.arange(1,11)
print(type(a2))
a2

<class 'numpy.ndarray'>


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Differences Between Python list and Numpy Array
1. Less memory
2. Fast
3. Convenient

In [14]:
# Numpy Array consumes less memory than List 
import numpy as np 
import sys 
 
x = list(range(100))

print("Size of each element of list in bytes: ", (sys.getsizeof(x[0]))) 
print("Size of the whole list in bytes: ",sys.getsizeof(x[0]) * len(x)) 

y=np.arange(100)
print("Size of each element in Numpy array in bytes: ",y.itemsize) 
print("Size of whole array in bytes: ",y.itemsize * y.size ) 


Size of each element of list in bytes:  24
Size of the whole list in bytes:  2400
Size of each element in Numpy array in bytes:  4
Size of whole array in bytes:  400


In [6]:
#Numpy Arrays are Faster than Python List
import time
size = 200000
list1 = list(range(size))
list2 = list(range(size))
start = time.time()
result = [x*y for x,y in zip(list1,list2)]
print("Computation Time for Python List: ",time.time()-start)

arr1 = np.arange(size)
arr2 = np.arange(size)
start = time.time()
result = arr1 * arr2
print("Computation Time for Numpy Array: ",time.time()-start)

Computation Time for Python List:  0.06981182098388672
Computation Time for Numpy Array:  0.010216712951660156


# Numpy arrays are convenient
## effect of operations on numpy arrays and python lists
import numpy as np 
a = np.array([1,2,3,4])+3 
print(a)

In [8]:
# Cannot add a scalar directly to the list items
print( [1,2,3,4]+ 3) 

TypeError: can only concatenate list (not "int") to list

In [9]:
l1 = [1,2,3,4]
l2 = []
for i in l1:
    l2.append(i+3)
l2
    

[4, 5, 6, 7]

In [10]:
[i+3 for i in l1]

[4, 5, 6, 7]

In [11]:
# Creating a 1-D Array
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [12]:
#2-dimensional array
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9], [9, 0, 1]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [9, 0, 1]])

In [13]:
# Find the shape of array(Shape gives number of rows by number of columns)

a2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2.shape) # rows * columns
print(a2.shape[0])#rows
print(a2.shape[1])#columns

(4, 3)
4
3


### Array Attributes
1. size
2. itemsize
3. dtype
4. ndim
5. shape

In [14]:
#reshape : Gives a new shape to an array without changing its data.
print(a2)

print("\n")

#Creating a 2-D array from 1-D array
arr1 = a2.reshape(3,4) # It'll create a 2D numpy array.
print(arr1)
print(arr1.size)
print(arr1.itemsize)
print(arr1.dtype)
print(arr1.ndim)
print(arr1.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
4
int32
2
(3, 4)


### Slicing: Use slicing to pull out the subarray from the orignial array.


In [15]:
a

array([4, 5, 6, 7])

In [16]:
# Indexing in 1D array
a[2]

6

In [17]:
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
# Indexing in 2D array
a2[1:,2]

array([ 6,  9, 12])

In [45]:
a2 = np.array([[10, 11, 12, 13, 14],
               [15, 16, 17, 18, 19],
               [20, 21, 22, 23, 24],
               [25, 26, 27, 28, 29]])

print(a2[1:,2:4])  # [[17 18]
                   #  [22 23]
                   #  [27 28]]

[[17 18]
 [22 23]
 [27 28]]


In [16]:
a2[1:3,:] # is the same as
a2[1:3]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
# Picking column
a2[:,1]

array([ 2,  5,  8, 11])

In [20]:
a2[0::2]

array([[1, 2, 3],
       [7, 8, 9]])

In [21]:
a2[0, 0::2]

array([1, 3])

In [22]:
a2[2, 2]

9

![Slicing](https://scipy-lectures.org/_images/numpy_indexing.png)

### Iterating through Array

In [44]:
a2

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [50]:
a2[0:-2,-2]

array([13, 18])

In [24]:
for i in a2:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [25]:
for i in a2.flat:
    print(i, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 

### Indexing with Boolean Array

In [26]:
a = np.array([[1,2], [3, 4], [5, 6]])

# Find the elements of a that are bigger than 2; this returns a numpy array of Booleans of the same shape as a, 
# where each slot of bool_idx tells whether that element of a is > 2.
bool_idx = (a > 2)   
                     
            
print(bool_idx)     

[[False False]
 [ True  True]
 [ True  True]]


In [27]:
a[bool_idx]

array([3, 4, 5, 6])

### Appending Arrays

In [18]:
#hstack: to append data horizontally(column wise)
a = np.arange(1,10).reshape(3,3)
b = np.arange(11,20).reshape(3,3)
np.hstack([a,b])

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [19]:
#vstack: to appened data vertically(row wise)
np.vstack([a,b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [20]:
#concatenate two arrays either row-wise or column-wise. 
#Concatenate function can take two or more arrays of the same shape and by default it concatenates row-wise i.e. axis=0
np.concatenate([a, b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [21]:
np.concatenate([a,b], axis = 0) # similar to vstack

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [26]:
np.concatenate([a,b], axis = 1) # similar to hstack

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [28]:
np.append(a,b, axis=1)

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

### Functions:
1. zeros()
2. ones()
3. full()
4. eye()
5. arange()
6. append()
7. linspace()
8. reshape()
9. ravel()


In [33]:
l=[1,2,3,1]
l.remove(2,3)

TypeError: remove() takes exactly one argument (2 given)

In [33]:
#zeros
z = np.zeros((2,2),dtype="int64")
z

array([[0, 0],
       [0, 0]], dtype=int64)

In [34]:
#ones
o = np.ones((2,2),dtype="int64")
o

array([[1, 1],
       [1, 1]], dtype=int64)

In [35]:
#full
f = np.full((2,2),55)
print(f)


[[55 55]
 [55 55]]


In [36]:
#full
f = np.full((2,2),'numpy')
print(f)

[['numpy' 'numpy']
 ['numpy' 'numpy']]


In [37]:
#eye()
e = np.eye(2,dtype="int32")
e


array([[1, 0],
       [0, 1]])

In [38]:
a = np.arange(start=1,stop=20,step=2)#similar to range(start,stop,step)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

![arange](https://files.realpython.com/media/fig-1.1d8bc9379e87.png)

### Getting Empty Arrays

- If you provide equal values for start and stop, then you’ll get an empty array
    * This is because counting ends before the value of stop is reached. Since the value of start is equal to stop, it can’t be reached and included in the resulting array as well.
- When start is greater than stop and step is positive, 
- Or when start is less than stop and step is negative

In [39]:
print(np.arange(2,2))
print(np.arange(6, 2, 1))
print(np.arange(2, 6, -1))

[]
[]
[]


In [40]:
a = np.arange(2,2)
a.shape

(0,)

In [41]:
a = np.append(a,int(input()))

ValueError: invalid literal for int() with base 10: ''

In [43]:
a

array([], dtype=int32)

In [44]:
a = np.append(a, [[1,2,3], [4,5,6]])
a

array([1, 2, 3, 4, 5, 6])

In [45]:
# Appending a column
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

arr2 = np.array([[400], [800]])

newArray = np.append(arr1, arr2, axis = 1)

print(newArray)

[[  1   2   3 400]
 [  4   5   6 800]]


In [46]:
# Appending a row
arr3 = np.array([[1, 2, 3], [4, 5, 6]])

newArray = np.append(arr3, [[50, 60, 70]], axis = 0)

print(newArray)

[[ 1  2  3]
 [ 4  5  6]
 [50 60 70]]


In [47]:
# delete an element from the array
a = np.array([1, 2, 3])

newArray = np.delete(a, 2, axis = 0)

print(newArray)

[1 2]


In [60]:
# Delete a row from the array
a = np.array([[1, 2, 3], [4, 5, 6], [10, 20, 30]])

newArray = np.delete(a, 1, axis = 0)

print(newArray)

[[ 1  2  3]
 [10 20 30]]


In [49]:
# a = np.array([1, 2, 3])

# if(a.size == 0):
#     print("The given Array is empty")
# else:
#     print("The array = ", a.size)

In [50]:
#linspace()-->returns evenly spaced numbers over a specified interval [start, stop]
l = np.linspace(1,10, 4)
l

array([ 1.,  4.,  7., 10.])

In [17]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [51]:
l2 = np.linspace(2,9.6, 5)
l2

array([2. , 3.9, 5.8, 7.7, 9.6])

In [52]:
# reshape
array2D = np.arange(10).reshape(2,5)
array2D

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [53]:
array2D

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30]])

In [55]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6, 10, 20, 30])

In [56]:
a.ravel()

array([ 1,  2,  3,  4,  5,  6, 10, 20, 30])

In [57]:
# print(np.array(a.flat))
# print(a.ravel())`

In [58]:
# Difference between ravel and flatten
print('Checking ravel()')
x = np.array([[40, 32, 67], [61, 79, 15]])
print('Original array:', x)
y = x.ravel()
print()
y[1] = 1000
print('Original array after making changes in flattened array:\n', x)
 
print('\nChecking flatten()')
a = np.array([[40, 32, 67], [61, 79, 15]])
print('Original array:\n', a)
b = a.flatten()
print()
b[1] = 1000
print('Original array after making changes in flattened array:\n', a)

Checking ravel()
Original array: [[40 32 67]
 [61 79 15]]

Original array after making changes in flattened array:
 [[  40 1000   67]
 [  61   79   15]]

Checking flatten()
Original array:
 [[40 32 67]
 [61 79 15]]

Original array after making changes in flattened array:
 [[40 32 67]
 [61 79 15]]


### Functions:
1. min()
2. max()
3. argmin()
4. argmax()
5. sum()
6. sqrt()
7. mean()
8. median()
9. std()

In [61]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30]])

In [62]:
print(a.min())
print(a.max())
print(a.argmin()) # return the index of min value
print(a.argmax()) # return the index of max value

1
30
0
8


In [63]:
print(a.sum())#sum of all the elements
print(a.sum(axis=1))#sum of column wise elements
print(a.sum(axis=0))#sum of row wise elements

81
[ 6 15 60]
[15 27 39]


In [64]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [3.16227766, 4.47213595, 5.47722558]])

In [65]:
#mean
np.mean(a)

9.0

In [66]:
#Median
np.median(a)

5.0

In [67]:
#Standard deviation
np.std(a)

9.201449161228174

In [68]:
#Transpose of an Array
a.T

array([[ 1,  4, 10],
       [ 2,  5, 20],
       [ 3,  6, 30]])

### Applying user-defined functions

In [69]:
list1 = list(range(1,20))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [70]:
result = [x*x-5 for x in list1]
print(result, end=' ')

[-4, -1, 4, 11, 20, 31, 44, 59, 76, 95, 116, 139, 164, 191, 220, 251, 284, 319, 356] 

In [30]:
def calculate(x):
    return x*x-5
print(calculate(2))

-1


In [31]:
calc = np.vectorize(calculate)
calc([1,2,3,4])
calc(b)

array([[ -5,  -4,  -1,   4,  11],
       [ 20,  31,  44,  59,  76],
       [ 95, 116, 139, 164, 191],
       [220, 251, 284, 319, 356]])

In [29]:
b = np.arange(0,20).reshape(4,5)
f = np.vectorize(lambda x : x*x-5)


In [73]:
a = np.array(list1)
f = np.vectorize(lambda x : x*x-5)
f(a)


array([ -4,  -1,   4,  11,  20,  31,  44,  59,  76,  95, 116, 139, 164,
       191, 220, 251, 284, 319, 356])

### Mathematical Operations(Element wise Operations): +,-,*,/,%


In [74]:
arr1 = np.arange(1,11)
arr2 = np.arange(10,20)
print(arr1 + arr2) 
print(arr2 - arr1)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 % arr2)

[11 13 15 17 19 21 23 25 27 29]
[9 9 9 9 9 9 9 9 9 9]
[ 10  22  36  52  70  90 112 136 162 190]
[0.1        0.18181818 0.25       0.30769231 0.35714286 0.4
 0.4375     0.47058824 0.5        0.52631579]
[ 1  2  3  4  5  6  7  8  9 10]


#### Matrix Multiplication(Dot Product):
- When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when

    - they are equal, or
    - one of them is 1, or
    - For N-dimensional arrays, it is a sum product over the last axis of a and the second-last axis of b. 

In [75]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
arr1.dot(arr2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [91]:
arr1 = np.arange(6).reshape(2,3)
arr2 = np.arange(12).reshape(3,4)
arr1.dot(arr2)

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

In [42]:
from numpy import random
r = np.random.RandomState(42)
print(r.rand()) #returns a random float between 0 and 1

0.3745401188473625


In [77]:
# Creating N-D Array with random float values

print(random.rand())
print("==" *15)

print(random.rand(2))
print("==" *15)
print(random.rand(2,3))


0.7339361850265946
[0.52039398 0.78912393]
[[0.82172274 0.06038784 0.19240318]
 [0.27589439 0.4331481  0.05525698]]


In [78]:
print(random.randint(100)) # Returns a random integer in the given range

# Creatig N-D Array with the random integer values
print(random.randint(100, size=(2)))
print("==" *15)
print(random.randint(100, size=(2,3)))
print("==" *15)
print(random.randint(100, size=(2,3,4)))



92
[79 49]
[[90 43 12]
 [60 94 31]]
[[[94 85 16 61]
  [44 90 75 59]
  [52 55 29 64]]

 [[54 18 67 38]
  [15 86 95 11]
  [45 67 29 21]]]


In [80]:
# Flattens the array
r = random.randint(50, size=(3,2)).ravel()
r

array([14, 29, 17, 24, 27, 33])

In [96]:
# Generate Random Number From Array with choice() method  based on an array of values

random.choice(r)

14

In [94]:
# Generate an array with the specified shape and elements from the given list
random.choice([1,2,3,4,5], size=(2,3))

array([[5, 1, 2],
       [4, 5, 2]])

```random.seed()```: Use random.seed() to initialize the pseudo-random number generator. Set seed to reproduce the data given by a pseudo-random number generator

In [100]:
random.seed(10)
random.choice(100)

9

In [34]:
a = np.array([])
a

array([], dtype=float64)

In [37]:
a = np.append(a,3)
a

array([3., 3.])

### Broadcasting:

In [6]:
np.arange(20)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [52]:
a = np.arange(20)
a[0:5] = 2
a

array([ 2,  2,  2,  2,  2,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
b = np.ones((3,3))
b[0][1] = 10
b

array([[ 1., 10.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [57]:
b = b+ np.arange(0,3)

In [58]:
b +20

array([[21., 22., 23.],
       [30., 31., 32.],
       [21., 22., 23.]])

In [59]:
b

array([[ 1.,  2.,  3.],
       [10., 11., 12.],
       [ 1.,  2.,  3.]])

In [60]:
b[[1,2,0]]

array([[10., 11., 12.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])

In [81]:
a = np.arange(3, 1)

In [79]:
a + b

ValueError: operands could not be broadcast together with shapes (0,) (3,3) 

In [82]:
a.shape

(0,)

In [77]:
b.shape

(3, 3)

In [84]:
import numpy as np

X = np.arange(8).reshape(4, 2)
y = np.arange(2).reshape(1, 2)  # create a 1x2 matrix
X * y


array([[0, 1],
       [0, 3],
       [0, 5],
       [0, 7]])

In [88]:
a = np.arange(9).reshape(3,3)
b = np.arange(3).reshape(1,3)
a*b

array([[ 0,  1,  4],
       [ 0,  4, 10],
       [ 0,  7, 16]])

In [89]:
a = np.arange(9).reshape(3,3)
b = np.arange(3,12).reshape(3,3)
a*b

array([[ 0,  4, 10],
       [18, 28, 40],
       [54, 70, 88]])

# random module

In [4]:
import numpy as np
np.random.rand() #0.26, 0.31, 0.10, 0.19

0.19151720946719042

In [5]:
import numpy as np
from numpy import random
r = np.random.RandomState(1) # 
a = r.rand() # 0 to 1
print(a)
np.round(a, decimals=1)

0.417022004702574


0.4

In [6]:
print(random.randint(100)) # returns the random integer in the specified range
arr = random.randint(100, size=(2,2))
arr

82


array([[89, 21],
       [ 0, 63]])

In [8]:
arr.ravel()

array([89, 21,  0, 63])

In [12]:
# choice() - allows to generate a random value based on an array of values.

random.choice(arr.ravel()) # arr is 2 D--> convert it into 1D array with help of ravel

21

In [5]:
random.seed(10)
random.choice([1,2,3,4,5], size=(2,2))

array([[2, 5],
       [1, 2]])

In [22]:
random.seed(34)
random.choice([1,2,3,4,5], size=(2,2))

array([[2, 3],
       [3, 2]])